import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    DATABASE_URL: z.url().describe('PostgreSQL connection string'),

    // Mkety Auth owns the application auth boundary. ZITADEL is the initial adapter.
    MKETY_AUTH_PROVIDER: z.literal('zitadel').default('zitadel'),
    MKETY_AUTH_ISSUER: z.url(),
    MKETY_AUTH_CLIENT_ID: z.string().min(1),
    MKETY_AUTH_CLIENT_SECRET: z.string().optional(),
    MKETY_AUTH_REDIRECT_URI: z.url(),
    MKETY_AUTH_POST_LOGOUT_REDIRECT_URI: z.url(),
    MKETY_AUTH_SESSION_SECRET: z.string().min(32),

    // Mkety AI Core. Disabled by default; provider credentials are optional.
    OPENAI_API_KEY: z.string().optional(),
    ANTHROPIC_API_KEY: z.string().optional(),
    MKETY_AI_PROVIDER: z.enum(['openai', 'groq', 'openrouter', 'custom']).default('openai'),
    MKETY_AI_MODEL: z.string().default('gpt-4o-mini'),
    GROQ_API_KEY: z.string().optional(),
    GROQ_BASE_URL: z.url().default('https://api.groq.com/openai/v1'),
    OPENROUTER_API_KEY: z.string().optional(),
    OPENROUTER_BASE_URL: z.url().default('https://openrouter.ai/api/v1'),
    MKETY_AI_API_KEY: z.string().optional(),
    MKETY_AI_BASE_URL: z.url().optional(),

    AWS_ACCESS_KEY_ID: z.string().optional(),
    AWS_SECRET_ACCESS_KEY: z.string().optional(),
    AWS_REGION: z.string().optional().default('us-east-1'),
    AWS_S3_BUCKET: z.string().optional(),
    S3_ENDPOINT: z.string().optional(),
    S3_PUBLIC_ENDPOINT: z.string().optional(),
    S3_ACCESS_KEY: z.string().optional(),
    S3_SECRET_KEY: z.string().optional(),
    S3_BUCKET: z.string().optional(),
    S3_REGION: z.string().optional().default('us-east-1'),
    SENTRY_DSN: z.url().optional(),
    ENABLE_AI_FEATURES: z.string().default('false').transform((val) => val === 'true'),
    ENABLE_TEST_LOGIN: z.string().default('false').transform((val) => val === 'true'),
    GITHUB_INTEGRATION_CLIENT_ID: z.string().optional(),
    GITHUB_INTEGRATION_CLIENT_SECRET: z.string().optional(),
    LINKEDIN_CLIENT_ID: z.string().optional(),
    LINKEDIN_CLIENT_SECRET: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.url().default('http://localhost:3000'),
    NEXT_PUBLIC_APP_NAME: z.string().default('Mkety'),
    NEXT_PUBLIC_SENTRY_DSN: z.url().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    MKETY_AUTH_PROVIDER: process.env.MKETY_AUTH_PROVIDER,
    MKETY_AUTH_ISSUER: process.env.MKETY_AUTH_ISSUER,
    MKETY_AUTH_CLIENT_ID: process.env.MKETY_AUTH_CLIENT_ID,
    MKETY_AUTH_CLIENT_SECRET: process.env.MKETY_AUTH_CLIENT_SECRET,
    MKETY_AUTH_REDIRECT_URI: process.env.MKETY_AUTH_REDIRECT_URI,
    MKETY_AUTH_POST_LOGOUT_REDIRECT_URI: process.env.MKETY_AUTH_POST_LOGOUT_REDIRECT_URI,
    MKETY_AUTH_SESSION_SECRET: process.env.MKETY_AUTH_SESSION_SECRET,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    MKETY_AI_PROVIDER: process.env.MKETY_AI_PROVIDER,
    MKETY_AI_MODEL: process.env.MKETY_AI_MODEL,
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    GROQ_BASE_URL: process.env.GROQ_BASE_URL,
    OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL: process.env.OPENROUTER_BASE_URL,
    MKETY_AI_API_KEY: process.env.MKETY_AI_API_KEY,
    MKETY_AI_BASE_URL: process.env.MKETY_AI_BASE_URL,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_REGION: process.env.AWS_REGION,
    AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_PUBLIC_ENDPOINT: process.env.S3_PUBLIC_ENDPOINT,
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
    S3_SECRET_KEY: process.env.S3_SECRET_KEY,
    S3_BUCKET: process.env.S3_BUCKET,
    S3_REGION: process.env.S3_REGION,
    SENTRY_DSN: process.env.SENTRY_DSN,
    ENABLE_AI_FEATURES: process.env.ENABLE_AI_FEATURES,
    ENABLE_TEST_LOGIN: process.env.ENABLE_TEST_LOGIN,
    GITHUB_INTEGRATION_CLIENT_ID: process.env.GITHUB_INTEGRATION_CLIENT_ID,
    GITHUB_INTEGRATION_CLIENT_SECRET: process.env.GITHUB_INTEGRATION_CLIENT_SECRET,
    LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
    LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
