import type { AppControlCenterModuleInput } from './schemas';

export type PlatformControlModuleStatus = 'planned' | 'foundation' | 'active' | 'protected';

export type PlatformControlModuleDomain =
  | 'mkety.com'
  | 'app.mkety.com'
  | 'api.mkety.com'
  | 'origin.mkety.com'
  | '*.mkety.app'
  | 'multi-domain'
  | 'internal';

export type PlatformControlModule = AppControlCenterModuleInput & {
  status: PlatformControlModuleStatus;
  domain: PlatformControlModuleDomain;
  editableScope: string[];
  protectedScope: string[];
  implementationNotes: string;
};

export const platformControlModules: PlatformControlModule[] = [
  {
    key: 'public-site-docs',
    label: 'Public Website & Docs',
    description: 'Manage mkety.com pages, docs, navigation, CTAs, FAQs, metadata, and public pricing display.',
    href: '/admin/platform-control/public-site',
    iconKey: 'globe',
    level: 1,
    enabled: true,
    requiredPermission: 'platform:content',
    sortOrder: 10,
    status: 'foundation',
    domain: 'mkety.com',
    editableScope: ['public pages', 'sections', 'navigation', 'docs', 'public pricing display', 'metadata', 'footer links'],
    protectedScope: ['application source code', 'backend business logic', 'security policy', 'billing ledger behavior'],
    implementationNotes: 'Private database-backed editorial drafts keep published pages visible while an operator saves and reopens an edit. Publishing validates and promotes the staged payload, then removes the draft after success.',
  },
  {
    key: 'app-experience',
    label: 'App Experience',
    description: 'Manage dashboard copy, workspace cards, onboarding text, empty states, quick links, and help links.',
    href: '/admin/platform-control/app-experience',
    iconKey: 'layout-dashboard',
    level: 1,
    enabled: true,
    requiredPermission: 'platform:app-experience',
    sortOrder: 20,
    status: 'foundation',
    domain: 'app.mkety.com',
    editableScope: ['dashboard headline', 'workspace cards', 'empty states', 'onboarding copy', 'support links'],
    protectedScope: ['workspace backend logic', 'tenant isolation', 'entitlement enforcement', 'routing middleware'],
    implementationNotes: 'Published app experience is read from the database with safe defaults; admin edits use a separate staged payload until publication.',
  },
  {
    key: 'plans-entitlements',
    label: 'Plans & Entitlements',
    description: 'Manage plan presentation, entitlement assignments, feature visibility, usage limits, and upgrade paths.',
    href: '/admin/platform-control/plans',
    iconKey: 'badge-check',
    level: 2,
    enabled: true,
    requiredPermission: 'platform:plans',
    sortOrder: 30,
    status: 'planned',
    domain: 'app.mkety.com',
    editableScope: ['plan labels', 'public plan display', 'feature visibility', 'upgrade copy', 'entitlement mapping proposals'],
    protectedScope: ['authorization engine', 'billing calculations', 'ledger mutation rules', 'unverified entitlement claims'],
    implementationNotes: 'Must remain aligned with enforceable backend entitlements before public pricing claims are expanded.',
  },
  {
    key: 'billing-ledger',
    label: 'Billing & Ledger',
    description: 'Review ledger entries and create controlled credit, refund, adjustment, and bonus transactions.',
    href: '/admin/platform-control/billing',
    iconKey: 'wallet',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:billing',
    sortOrder: 40,
    status: 'protected',
    domain: 'app.mkety.com',
    editableScope: ['controlled adjustments', 'refund requests', 'bonus grants', 'ledger review notes'],
    protectedScope: ['direct balance editing', 'destructive ledger mutation', 'frontend invoice calculations', 'payment-provider secrets'],
    implementationNotes: 'Ledger must remain append-oriented and auditable. Admin actions create transactions, never silent balance edits.',
  },
  {
    key: 'payments',
    label: 'Payments',
    description: 'Manage payment-provider business settings, checkout presentation, currencies, and commercial FX pricing.',
    href: '/admin/platform-control/payments',
    iconKey: 'credit-card',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:billing',
    sortOrder: 45,
    status: 'active',
    domain: 'multi-domain',
    editableScope: ['commercial FX rates', 'FX markup', 'provider presentation settings', 'payment readiness visibility'],
    protectedScope: ['provider secrets', 'webhook verification', 'settlement rules', 'billing ledger mutation', 'customer-supplied pricing'],
    implementationNotes: 'Business payment configuration is database-backed. Secrets remain runtime-only and settlement remains server-verified.',
  },
  {
    key: 'mail-operations',
    label: 'Mkety Mail',
    description: 'Operate Mail tenants, reconcile the commercial catalog, manage workspace state, domain sending/routing readiness, and inspect product capacity without exposing provider secrets.',
    href: '/admin/platform-control/mail',
    iconKey: 'mail',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:plans',
    sortOrder: 47,
    status: 'active',
    domain: 'multi-domain',
    editableScope: ['Mail catalog reconciliation', 'tenant Mail status', 'onboarding state', 'domain sending/routing state', 'mail DNS readiness state', 'customer-safe commercial configuration'],
    protectedScope: ['provider secrets', 'verified payment settlement', 'immutable billing history', 'cross-tenant message content', 'silent quota bypass', 'canonical price mutation without an explicit version change'],
    implementationNotes: 'Mail operations are protected by the global Platform Control allowlist plus plan/billing permissions. Billing remains authoritative for purchased Mail tiers.',
  },
  {
    key: 'media-connector',
    label: 'Mkety Media Connector',
    description: 'Link Mkety tenants to existing standalone Mkety Media workspaces without moving Media runtime, billing or secrets into the Platform.',
    href: '/admin/platform-control/media',
    iconKey: 'image',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:plans',
    sortOrder: 47,
    status: 'active',
    domain: 'multi-domain',
    editableScope: ['tenant-to-Media workspace reference', 'link status', 'operator verification note'],
    protectedScope: ['Media credentials', 'Media subscription mutation', 'Media invoice state', 'unverified customer self-linking', 'standalone Media runtime'],
    implementationNotes: 'The connector stores only an admin-verified non-secret external workspace reference. Media remains commercially and operationally authoritative until its runtime exposes an accepted sync/SSO API.',
  },
  {
    key: 'ai-operations',
    label: 'Mkety AI Operations',
    description: 'Control Enterprise AI limits, rate versions, model readiness, spend protection, and the emergency inference kill switch without changing application code.',
    href: '/admin/platform-control/ai-operations',
    iconKey: 'sparkles',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:plans',
    sortOrder: 48,
    status: 'active',
    domain: 'multi-domain',
    editableScope: [
      'future AI rate-card versions',
      'request and output safety limits',
      'reservation lifetime',
      'customer-safe model readiness visibility',
      'emergency inference disable',
    ],
    protectedScope: [
      'postpaid overage enablement',
      'historical rate mutation',
      'provider secrets',
      'tenant isolation',
      'commercial admission bypass',
      'production model promotion without release gates',
    ],
    implementationNotes: 'Enterprise AI is prepaid-only and fail-closed. Rate changes create new effective-dated versions; historical billable rates are never silently rewritten.',
  },
  {
    key: 'deployments-domains',
    label: 'Deployments & Domains',
    description: 'Review non-production deployment requests, approve or reject one-time candidate execution, and inspect deployment history.',
    href: '/admin/platform-control/deployments-domains',
    iconKey: 'cloud',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:deployments',
    sortOrder: 50,
    status: 'foundation',
    domain: 'multi-domain',
    editableScope: ['candidate deployment approvals', 'approval review notes', 'request status visibility', 'deployment history'],
    protectedScope: ['production execution', 'DNS mutation', 'custom-domain mutation', 'deployment engine code', 'Cloudflare secrets', 'OCI secrets', 'origin routing internals'],
    implementationNotes: 'Approval authorizes one later customer-triggered isolated candidate execution. Production, DNS, custom domains and rollback remain outside this slice.',
  },
  {
    key: 'domains-routing',
    label: 'Mkety Domains & DNS',
    description: 'Operate domain registration, customer pricing, nameservers, DNS, managed hostnames, custom-domain validation, and routing from one Mkety control surface.',
    href: '/admin/platform-control/domains-routing',
    iconKey: 'route',
    level: 3,
    enabled: true,
    requiredPermission: 'platform:deployments',
    sortOrder: 60,
    status: 'active',
    domain: 'multi-domain',
    editableScope: ['registrar connection', 'customer price markup', 'nameservers', 'WHOIS privacy policy', 'DNS zones', 'CNAME target', 'TLS floor', 'managed DNS proxy policy', 'custom-domain review'],
    protectedScope: ['decrypted provider secrets', 'unverified registration or renewal', 'origin routing changes without review', 'unapproved hostnames', 'customer app isolation'],
    implementationNotes: 'Mkety Domains and DNS use database-backed platform connections with encrypted credentials, fixed-egress registrar traffic, and protected Cloudflare routing actions. Public customers interact with Mkety rather than underlying providers.',
  },
  {
    key: 'auth-gateway',
    label: 'Auth Gateway',
    description: 'Monitor the central Mkety identity/access gateway, product audiences, JWKS status, key rotation metadata, and access issuance outcomes.',
    href: '/admin/platform-control/auth-gateway',
    iconKey: 'key-round',
    level: 4,
    enabled: true,
    requiredPermission: 'platform:security',
    sortOrder: 70,
    status: 'planned',
    domain: 'internal',
    editableScope: ['audience registry notes', 'JWKS visibility', 'rotation readiness status', 'issuance monitoring'],
    protectedScope: ['private keys', 'token signing code', 'caller-supplied claims', 'raw ZITADEL coupling'],
    implementationNotes: 'Documented as architecture only in this batch. Real signing/JWKS endpoints require separate security-focused implementation.',
  },
  {
    key: 'security-audit',
    label: 'Security & Audit',
    description: 'View security events, audit logs, role changes, session actions, webhook events, and sensitive operations.',
    href: '/admin/platform-control/security',
    iconKey: 'shield',
    level: 4,
    enabled: true,
    requiredPermission: 'platform:security',
    sortOrder: 80,
    status: 'protected',
    domain: 'internal',
    editableScope: ['audit review', 'session revocation request flows', 'security event triage notes', 'role-change review'],
    protectedScope: ['tenant isolation rules', 'security bypasses', 'secret exposure', 'destructive audit log edits'],
    implementationNotes: 'Audit visibility may be exposed, but audit history must remain append-oriented and tamper-resistant.',
  },
];
